angular.module('MineModule',['ui.router'])
.config(function($stateProvider,$urlRouterProvider){
	$stateProvider
	.state('mine',{
		url:'/mine',
		templateUrl:'component/mine/mine.html',
		css:'component/mine/mine.css'
	})
})