angular.module('productDetail',['ngRoute'])
.config(['$routeProvider',function($routeProvider){
	$routeProvider
	.when('/product_detail',{
		templateUrl:'component/products_detail/product_detail.html',
		controller:'productDetailCtrl',
		css:'component/products_detail/product_detail.css'
	})
}])
.controller('productDetailCtrl',['$scope',function($scope){
	$scope.detailInfo=JSON.parse(localStorage.getItem('detailInfo'));
}])
